DROP TABLE IF EXISTS TBL_EMPLOYEES;

CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE TBL_USER (
    id INT AUTO_INCREMENT NOT NULL,
    userid VARCHAR(50) PRIMARY KEY,
    pass VARCHAR(20) NOT NULL,
    role VARCHAR(15) NOT NULL
);

CREATE TABLE TBL_SWEETS (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) PRIMARY KEY,
    img VARCHAR(2000) NOT NULL,
    qty VARCHAR(15) NOT NULL,
    price DOUBLE(8) NOT NULL
);
